language: cpp
sudo: required
complier:
- g++
os:
- linux
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
      - google-cloud
    packages:
      - cmake-data
      - cmake
      - g++-4.9
      - gcc-4.9
env: CXX_FLAGS=-std=c++11
before_script:
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - cd googletest
  - mkdir mybuild
  - cd mybuild
  - cmake .. -DCMAKE_CXX_FLAGS=$CXX_FLAGS
  - make
  - cp lib/lib* /usr/lib/
  - cd ..
  - cp -a include/gtest /usr/include/
script: 
  - cd ..
  - cd ..
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_FLAGS=$CXX_FLAGS
  - make
  - ./fp_test
