language: cpp
sudo: required
complier:
- g++
os:
- linux
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
      - google-cloud
    packages:
      - cmake-data
      - cmake
env: CXX_FLAGS=-std=c++11
install:
  - sudo apt-get install -qq g++-4.9
  - export CXX="g++-4.9"
before_script:
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - cd googletest
  - mkdir mybuild
  - cd mybuild
  - cmake ..
  - make
  - sudo make install
script: 
  - cd ..
  - cd ..
  - cd ..
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./fp_test
