language: c++
sudo: required
complier:
- gcc
os:
- linux
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
      - google-cloud
    packages:
      - g++-4.9
      - cmake-data
      - cmake
      - googletest
script: 
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./fp_test
