language: cpp
sudo: required
complier:
- g++
os:
- linux
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - g++-4.9
      - gcc-4.9
install:
  - chmod 777 scripts/install_gtest.sh
  - ./scripts/install_gtest.sh
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./fp_test
