#pragma once

namespace cl
{

enum FunctionType
{
    T_BASE_FUNCTION,
    T_INDEPENDENT_VARIABLE,
    T_CONSTANT_FUNCTION,
    T_ADD_FUNCTION,
    T_MINUS_FUNCTION,
    T_MULTIPLY_FUNCTION,
    T_DIVIDE_FUNCTION,
    T_POWER_FUNCTION,
    T_LN_FUNCTION,
    T_SIN_FUNCTION,
    T_COS_FUNCTION,
    T_TAN_FUNCTION,
    T_PICEWISE_FUNCTION
};

}